ADDED: used tmux pane for foreground shell commands

diff --git a/config/ftl/etc/extra_commands/shell b/config/ftl/etc/extra_commands/shell
--- a/config/ftl/etc/extra_commands/shell
+++ b/config/ftl/etc/extra_commands/shell
@@ -37,18 +37,30 @@ shell_command()
 # todo: pass selection to session context
 # todo: keep window open
 
-[[ "$1" =~ ^-s ]] &&
+[[ "$1" =~ ^-b ]] &&
 	{
-	[[ "$1" =~ ^-sl ]] && for n in "${selection[@]}" ; do tscommand "${1#-sl}" "-e n=${n@Q}" ; done || { tscommand "${1#-s}" "-e n=${n@Q}" ; }
+	[[ "$1" =~ ^-bl ]] && for n in "${selection[@]}" ; do tscommand "${1#-bl}" "-e n=${n@Q}" ; done || { tscommand "${1#-b}" "-e n=${n@Q}" ; }
 	cdir ; return
 	}
 
 tcpreview ; s="${selection[@]}" ; echo -en '\e[?1049l'
 
-[[ "$1" =~ ^-l ]] && for n in "${selection[@]}" ; do eval "echo -e '\e[2;33m[$(date -R)] $PWD > $1\e[m' ; ${1#-l} ; echo «$?»" ; done \
-	|| eval "echo -e '\e[2;33m[$(date -R)] $PWD > $1\e[m' ; $1 ; echo «$?»"
 
-read -sn 1 ; echo -en '\e[?1049h' ; cdir
+((has_bash_window)) || { tmux new -A -d -s ftl$$ ; tmux neww -t ftl$$ -n ftl$$_bash ; sleep 0.2 ; has_bash_window=1 ; }
+
+[[ "$1" =~ ^-l ]] && 
+	{
+	for n in "${selection[@]}"
+		do
+			echo "cd '$PWD' ; echo -e '\e[2;33m[$(date -R)] $PWD\n\e[0;33mftl> $@ \e[m' ; ${@#-l} ; echo -e '\n\e[2;33mExit code: $?\e[m'" >$fs/bash_command
+			tmux send -t ftl$$:ftl$$_bash ". $fs/bash_command" Enter
+		done
+
+	} ||
+	{
+	echo "cd '$PWD' ; echo -e '\e[2;33m[$(date -R)] $PWD\n\e[0;33mftl> $@ \e[m' ; ${@#-l} ; echo -e '\n\e[2;33mExit code: $?\e[m'" >$fs/bash_command
+	tmux send -t ftl$$:ftl$$_bash ". $fs/bash_command" Enter
+	}
 }
 
 # vim: set filetype=bash :
